name: pipeline
channels:
  - defaults
dependencies:
  - aiosqlite=0.21.0
  - aom=3.6.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - eigen=3.4.0
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - fuzzywuzzy=0.18.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - greenlet=3.1.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - librsvg=2.56.3
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mysql=8.4.0
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - pango=1.50.7
  - pcre2=10.42
  - pip=25.1
  - pixman=0.40.0
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-levenshtein=0.12.2
  - qt-main=5.15.2
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tesseract=5.2.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - easyocr==1.7.2
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - filelock==3.18.0
      - fsspec==2025.3.2
      - h11==0.16.0
      - hf-xet==1.1.0
      - huggingface-hub==0.31.1
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.6
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pdf2image==1.17.0
      - pillow==11.2.1
      - pyclipper==1.3.0.post6
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pytesseract==0.3.13
      - python-bidi==0.6.6
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scipy==1.13.1
      - shapely==2.0.7
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.14.0
      - tifffile==2024.8.30
      - tokenizers==0.21.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - transformers==4.51.3
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - uvicorn==0.34.2
